language: node_js
node_js:
  - 12

services: 
  - docker

before_script:
  - echo "before run script"

install:
  - echo "build, tagging and push docker"

script:
  - docker --version
  # build
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # tag
  - docker tag udagram-frontend honaz140/udagram-frontend:v1
  - docker tag udagram-api-user honaz140/udagram-api-user:v1
  - docker tag udagram-api-feed honaz140/udagram-api-feed:v1
  - docker tag udagram-reverseproxy honaz140/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push
  - docker push udagram-frontend/udagram-frontend:v1
  - docker push udagram-api-user/udagram-api-user:v1
  - docker push udagram-api-feed/udagram-api-feed:v1
  - docker push udagram-reverseproxy/udagram-reverseproxy:v1