apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
        - image: honaz140/udagram-reverseproxy:v1
          name: reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "1024Mi"
              cpu: "300m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
